version: '3.8'

services:
  # Servi√ßo do Banco de Dados
  db:
    image: postgres:15
    container_name: galeria_postgres
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: galeria_db
      POSTGRES_USER: usuario_galeria
      POSTGRES_PASSWORD: senha_secreta
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: